ner:
  build: ./freme-ner
  command: java -Xms5g -Xmx5g -jar /opt/freme-ner/freme-ner-dev-0.8-full.jar
  ports:
    - "7002:7002"   
  links:
   - db  
   - solr
solr:
  build: ./freme-ner-solr
  ports:
    - "8983:8983"   
db:
  image: mysql
  ports:
    - "3306:3306"  
  environment:
    MYSQL_ROOT_PASSWORD: freme
    MYSQL_USER: freme
    MYSQL_PASSWORD: freme
    MYSQL_DATABASE: freme
