ner:
  build: ./freme-ner
  command: /opt/freme-ner/bin/freme-ner.sh
  ports:
    - "7002:7002"   
  links:
   - db  
   - solr
solr:
  build: ./freme-ner-solr
  ports:
    - "8983:8983" 
  links:
   - db    
db:
  image: mysql
  ports:
    - "3306:3306"  
  environment:
    MYSQL_ROOT_PASSWORD: freme
    MYSQL_USER: freme
    MYSQL_PASSWORD: freme
    MYSQL_DATABASE: freme
